### ISSUE TITLE
Can't use multiplier suffix (Gi, Ti) on `SCALE_UP_MAX_SIZE`

### ISSUE THREAD

**Issue by lucasfcnunes** [DevOps-Nirvana/Kubernetes-Volume-Autoscaler#20]
**Is your feature request related to a problem? Please describe.**

```console
2023-11-23T11:48:38.529068781Z Traceback (most recent call last):
2023-11-23T11:48:38.529130552Z   File "/app/./main.py", line 4, in <module>
2023-11-23T11:48:38.529156651Z     from helpers import INTERVAL_TIME, PROMETHEUS_URL, DRY_RUN, VERBOSE, get_settings_for_prometheus_metrics, is_integer_or_float, print_human_readable_volume_dict
2023-11-23T11:48:38.529169656Z   File "/app/helpers.py", line 34, in <module>
2023-11-23T11:48:38.529186090Z     SCALE_UP_MAX_SIZE = int(getenv('SCALE_UP_MAX_SIZE') or 16000000000000)           # How many bytes is the maximum disk size that we can resize up, default is 16TB for EBS volumes in AWS (in bytes, so 16000000000000)
2023-11-23T11:48:38.529293525Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-23T11:48:38.529335419Z ValueError: invalid literal for int() with base 10: '300Gi'
```

**Describe the solution you'd like**

Be able to use suffixes as defined in https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/blob/f7b773f1674bed8bca111ecc1f2ffeedac62cc98/helpers.py#L200-L241

**Comment by AndrewFarley** [comment]
This is an awesome feature request!  Will definitely try to make this happen!
